fix: django42 upgrade support added
openedx/edx-bulk-grades pull request #155
Opened 2023-06-14 14:20 UTC by zubairshakoorarbisoft

Added django42 upgrade support, to have more context on it please refer to the following [issue](https://github.com/edx/upgrades/issues/146)

2023-06-15 10:58 UTC, UsamaSadiq approved these changes

2023-07-25 10:28 UTC, UsamaSadiq requested changes

2023-07-25 12:28 UTC, zubairshakoorarbisoft commented on .github/workflows/ci.yml
> +        if: matrix.python-version == '3.8' && matrix.toxenv=='django42-celery50'
changes added @UsamaSadiq

2023-07-25 13:56 UTC, awais786 approved these changes

2023-07-25 14:11 UTC, merged